name: Phantom Scheduler

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Execute crawl.sh
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: bash crawl.sh

    - name: Call deploy hook
      env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
      run: curl -X POST ${{ secrets.DEPLOY_HOOK_URL }}