name: Server Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies & build
      env:
          SAVE_CRAWLS: 0
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          CHUNK_SIZE: 50
          CHUNK_LIMIT: 50
      run: |
        python -m venv .env
        source .env/bin/activate
        pip install -r requirements.txt
        bash build.sh 6
      
    - name: Local Flask server Test
      run: |
        source .env/bin/activate
        python3 server.py &
        sleep 5
        curl -f http://localhost:5000/
        echo "Flask test completed"
    
    - name: Test Gunicorn server
      run: |
        source .env/bin/activate
        gunicorn -w 4 server:app &
        sleep 5
        curl -f http://localhost:8000/
        echo "Gunicorn test completed"
